version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  redis-gui:
    image: marian/rebrow
    hostname: redis-gui
    ports:
      - "5001:5001"
    networks:
      - redis-net
    depends_on:
      - redis

networks:
  redis-net:

volumes:
  redis-data: